version: '3.8'

services:
  mongo1:
    image: mongo:latest
    container_name: mongo1
    command: mongod --replSet rs0 --bind_ip_all --keyFile /opt/keyfile/mongo-keyfile --auth
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo1:/data/db
      - ./scripts:/scripts
      - ./keyfile:/opt/keyfile
    networks:
      - mongo_network
    healthcheck:
      test: mongosh --port 27017 -u bienpx -p 3MCr09mTRq9NOWdhdwgf --authenticationDatabase admin --eval "db.adminCommand('ping').ok" --quiet | grep 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
      
  mongo2:
    image: mongo:latest
    container_name: mongo2
    command: mongod --replSet rs0 --bind_ip_all --keyFile /opt/keyfile/mongo-keyfile --auth
    ports:
      - "27018:27017"
    volumes:
      - ./data/mongo2:/data/db
      - ./keyfile:/opt/keyfile
    networks:
      - mongo_network
    healthcheck:
      test: mongosh --port 27018 -u bienpx -p 3MCr09mTRq9NOWdhdwgf --authenticationDatabase admin --eval "db.adminCommand('ping').ok" --quiet | grep 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
      
  mongo3:
    image: mongo:latest
    container_name: mongo3
    command: mongod --replSet rs0 --bind_ip_all --keyFile /opt/keyfile/mongo-keyfile --auth
    ports:
      - "27019:27017"
    volumes:
      - ./data/mongo3:/data/db
      - ./keyfile:/opt/keyfile
    networks:
      - mongo_network
    healthcheck:
      test: mongosh --port 27019 -u bienpx -p 3MCr09mTRq9NOWdhdwgf --authenticationDatabase admin --eval "db.adminCommand('ping').ok" --quiet | grep 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

networks:
  mongo_network:
    driver: bridge 