version: '3'

services:
  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=password
      - NODE_ENV=production
      - N8N_ENCRYPTION_KEY=your-secure-encryption-key-here
      - WEBHOOK_URL=https://your-domain.com
    volumes:
      - ~/.n8n:/home/node/.n8n
    user: "${UID:-1000}:${GID:-1000}" 